# TEST_BLOCK
- test:
    timeout:
      minutes: 20
    definitions:
    - repository: https://gitlab.com/cip-project/cip-testing/cip-security-tests.git
      from: git
      branch: master
      path: iec-security-tests/Singlenode-TestDefinition.yaml
      name: IEC_Security_Tests
